//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsDbEntities : DbContext
    {
        public CarsDbEntities()
            : base("name=CarsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carsTable> carsTable { get; set; }
        public virtual DbSet<rezervasyonlar> rezervasyonlar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
    }
}
