//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carsTable
    {
        public int Id { get; set; }
        public string CarsName { get; set; }
        public string CarsModel { get; set; }
        public Nullable<System.DateTime> carsDate { get; set; }
        public string carsGear { get; set; }
        public string carsGas { get; set; }
        public string carsPrice { get; set; }
    }
}
