//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public string Tckimlik { get; set; }
        public string adsoyad { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public string cinsiyet { get; set; }
        public string telefon { get; set; }
        public string sifre { get; set; }
    }
}
