//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervasyonlar
    {
        public int rezervasyonId { get; set; }
        public Nullable<int> aracıd { get; set; }
        public string tc { get; set; }
        public string adsoyad { get; set; }
        public Nullable<System.DateTime> AlmaTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public string iptalmi { get; set; }
        public Nullable<System.DateTime> iptaltarihi { get; set; }
    }
}
